name: lint

on: [push, pull_request]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: 'Install project'
      run: |
        python3 --version
        python3 -m pip install -e ".[test]"
    - name: 'Test with ruff'
      run: |
        ruff check
